### ISSUE TITLE
Allow other projections as input

### ISSUE THREAD

**Issue by jyucsiro** [GeoscienceAustralia/AusPIX_DGGS#6]
Currently the Auspix engine uses WGS84 as the default projection for coordinates. Propose that this can be broadened out to at least GDA94 or the standard datum for Australia.

**Comment by bellie888** [comment]
as discussed, WGS84 works good because it is worldwide including Antarctica. Other projections can be designed and added to the list of projections in the engine if desired but out of scope for this contract I think. We would need a specialist to write the GDA94 module.
