### ISSUE TITLE
Use standard shapefile libs rather than own shapefile module

### ISSUE THREAD

**Issue by jyucsiro** [GeoscienceAustralia/AusPIX_DGGS#7]
The current callablemodules lib uses its own shapefile module. This was introduced as a bit of legacy code. Propose we replace this with pyshp (https://github.com/GeospatialPython/pyshp) and/or Shapely (https://github.com/Toblerity/Shapely), which are well known libraries for the required functionality and well documented/maintained.

**Comment by bellie888** [comment]
Yes pyShp is the "repo" for shapefile. Local version of shapefile has been deleted.
Note: shapley dosn't carry spatial data attributes so geojason is preferred for that sort of work.

Cheers
Joe
